test.moveAde<-function()
{
	data <- move(system.file("extdata","ricky.csv.gz",package="move"))
	dataSp<-spTransform(data, center=T)
	dataLtraj<-as(dataSp, 'ltraj')
	dataBack<-as(dataLtraj, 'Move')
	checkEqualsNumeric(coordinates(dataSp), coordinates(dataBack), checkNames=F)
	checkEquals(timestamps(dataSp), timestamps(dataBack))
	spLtraj<-move2ade(dataSp)
	require(adehabitatLT)
	a<-as(simm.crw(1:100),'Move')
	checkTrue(validObject(a))
	a<-as(a, 'ltraj')
	checkTrue(validObject(a))
	a<-as(simm.crw(1:100, id=gl(25,4)),'MoveStack')
	checkTrue(validObject(a))
	a<-as(a, 'ltraj')
	checkTrue(validObject(a))
}
